name: Dart CI

on:
  push:
    branches: [ main, relase/*, develop, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Flutter ${{ matrix.flutter-version }}
      id: flutter
      if: "!startsWith(matrix.bot, 'dart')"
      uses: DanTup/gh-actions/setup-flutter@master
      with:
        channel: ${{ matrix.flutter-version }}
    - name: Install dependencies
      run: flutter pub get
    - name: Run tests
      run: pub run test
