name: Dart CI

on:
  push:
    branches: [ main, relase/*, develop, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: setup-flutter
    # You may pin to the exact commit or the version.
    # uses: takuyaohashi/setup-flutter@13485697cd6c4f77aca5364e1bad821fe627ad13
      uses: takuyaohashi/setup-flutter@v1  
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
